[features]
seeds = false
skip-lint = false
[programs.devnet]
sendsolfromapda = "Gm9srn94QiQyfcz28y6g54F8zM6SwqgpPzNe7XMN91i8"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/mateo/.config/solana/id.json"

[scripts]
create = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/CreatePDA.ts"
send = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/SendSOLfromPDA.ts"